var app = new Vue({
    el:"#app",
    data:{
       foods:[
           {
               name:"大米",
               price:8,
               company:"a公司"
            },
            {
                name:"红米",
                price:10,
                company:"b公司"
             },
             {
                name:"黑米",
                price:15,
                company:"c公司"
             },
       ]
    }
})